import type { RemindStore } from './store.js';
/** 一次性注入本插件全部样式的 <style> 文本；随 client fiber 卸载移除。 */
export declare const INFORM_STYLE_SHEET = "\n.dsh-inform-stack{position:fixed;top:16px;right:16px;display:flex;flex-direction:column;gap:8px;width:320px;max-width:calc(100vw - 32px);z-index:10000;pointer-events:none}\n.dsh-inform-card{pointer-events:auto;background:#ffffff;color:#1f2328;border:1px solid rgba(0,0,0,0.14);border-radius:10px;box-shadow:0 6px 24px rgba(0,0,0,0.14);padding:10px 12px}\n.dsh-inform-card[data-kind=\"complete\"]{border-left:3px solid #22a06b}\n.dsh-inform-card[data-kind=\"approval\"]{border-left:3px solid #d97706}\n.dsh-inform-card[data-kind=\"question\"]{border-left:3px solid #3b82f6}\n@media (prefers-color-scheme:dark){.dsh-inform-card{background:#22272e;color:#e6edf3;border-color:rgba(255,255,255,0.14)}}\n.dsh-inform-header{display:flex;align-items:center;gap:8px;margin-bottom:4px}\n.dsh-inform-badge{flex-shrink:0;font-size:11px;line-height:16px;padding:0 7px;border-radius:999px;color:#fff;white-space:nowrap}\n.dsh-inform-badge[data-kind=\"complete\"]{background:#22a06b}\n.dsh-inform-badge[data-kind=\"approval\"]{background:#d97706}\n.dsh-inform-badge[data-kind=\"question\"]{background:#3b82f6}\n.dsh-inform-title{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600}\n.dsh-inform-close{flex-shrink:0;border:none;background:transparent;color:inherit;opacity:.55;cursor:pointer;font:inherit;line-height:1;padding:2px}\n.dsh-inform-close:hover,.dsh-inform-close:focus-visible{opacity:1}\n.dsh-inform-summary{margin:0;word-break:break-word;white-space:pre-wrap}\n.dsh-inform-detail{margin:6px 0 0;opacity:.75;white-space:pre-wrap;word-break:break-word;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}\n";
export interface ToastStackProps {
    /** slot inject face 注入的仓库。 */
    remind: RemindStore;
}
/** 注册进 `shell.overlay` 的条目组件：uiPopup 关闭（默认）或无提醒时渲染 null，不占布局。 */
export declare function ToastStack({ remind }: ToastStackProps): React.ReactNode;
